[2022-01-14 00:19:27,848] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag_anp.rfn_sales_oil_derivative manual__2022-01-14T00:15:21.890329+00:00 [queued]>
[2022-01-14 00:19:27,866] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag_anp.rfn_sales_oil_derivative manual__2022-01-14T00:15:21.890329+00:00 [queued]>
[2022-01-14 00:19:27,867] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 00:19:27,867] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-14 00:19:27,867] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 00:19:27,884] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): rfn_sales_oil_derivative> on 2022-01-14 00:15:21.890329+00:00
[2022-01-14 00:19:27,891] {standard_task_runner.py:52} INFO - Started process 2841 to run task
[2022-01-14 00:19:27,896] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag_anp', 'rfn_sales_oil_derivative', 'manual__2022-01-14T00:15:21.890329+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/my_dag_anp.py', '--cfg-path', '/tmp/tmpmjf12tff', '--error-file', '/tmp/tmpphsoktmd']
[2022-01-14 00:19:27,897] {standard_task_runner.py:77} INFO - Job 68: Subtask rfn_sales_oil_derivative
[2022-01-14 00:19:28,005] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag_anp.rfn_sales_oil_derivative manual__2022-01-14T00:15:21.890329+00:00 [running]> on host 9ef8a6cbe880
[2022-01-14 00:19:28,095] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag_anp
AIRFLOW_CTX_TASK_ID=rfn_sales_oil_derivative
AIRFLOW_CTX_EXECUTION_DATE=2022-01-14T00:15:21.890329+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-14T00:15:21.890329+00:00
[2022-01-14 00:19:28,483] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils.py", line 372, in run_rfn_sales_oil_derivative
    shutil.rmtree(sink)
  File "/usr/local/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/sink/rfn/rfn_sales_oil_deriv.parquet'
[2022-01-14 00:19:28,507] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=my_dag_anp, task_id=rfn_sales_oil_derivative, execution_date=20220114T001521, start_date=20220114T001927, end_date=20220114T001928
[2022-01-14 00:19:28,527] {standard_task_runner.py:92} ERROR - Failed to execute job 68 for task rfn_sales_oil_derivative
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils.py", line 372, in run_rfn_sales_oil_derivative
    shutil.rmtree(sink)
  File "/usr/local/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/sink/rfn/rfn_sales_oil_deriv.parquet'
[2022-01-14 00:19:28,550] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-14 00:19:28,604] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
